### ISSUE TITLE
Missing file preventing HCQT tests from passing

### ISSUE THREAD

**Issue by cjacoby** [ejhumphrey/harmonic-cnn#24]
`ismir2016-wcqt/tests/uneven_hcqt.flac

@ejhumphrey I suspect you have this somewhere not checked in. But I could deal with it in other ways if I had to.

**Comment by cjacoby** [comment]
FYI; This is blocking #20.

**Comment by ejhumphrey** [comment]
doesn't appear to be on my compute machine, will look into this later

**Comment by cjacoby** [comment]
I pytest.mark.xfail'd this sucker; probably still best to fix it, but not blocking anymore.
